# Generated by Django 3.1.4 on 2020-12-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imageanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mage',
            new_name='mage2',
        ),
    ]
