# Generated by Django 3.1.4 on 2020-12-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imageanalysis', '0002_auto_20201221_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='mage2',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
